# Generated by Django 4.2.16 on 2024-10-11 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("example", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weatherlocation",
            name="latitude",
            field=models.DecimalField(
                decimal_places=10,
                help_text="Latitude of the location, decimal (−90; 90)",
                max_digits=12,
                verbose_name="Latitude",
            ),
        ),
        migrations.AlterField(
            model_name="weatherlocation",
            name="longitude",
            field=models.DecimalField(
                decimal_places=10,
                help_text="Longitude of the location, decimal (−180; 180)",
                max_digits=13,
                verbose_name="Longitude",
            ),
        ),
    ]
